### ISSUE TITLE
Ошибка при парсинге лога pdaemon.txt

### ISSUE THREAD

**Issue by npatyur** [OSLL/mooc-lp-statistics#102]
https://github.com/OSLL/mooc-lp-statistics/files/972736/pdaemon.txt

Environment:

Request Method: GET
Request URL: http://mooc-lp-statistics/

Django Version: 1.9.4
Python Version: 2.7.6
Installed Applications:
['django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'App',
'rest_framework']
Installed Middleware:
['django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware']

Traceback:

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
149. response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
147. response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/mooc-lp-statistics/App/views.py" in home
32. list_of_result_lists = App.another_functions.parsing()

File "/var/www/mooc-lp-statistics/App/another_functions.py" in parsing
80. list_of_result_lists += [razbor_stroki(line)]

File "/var/www/mooc-lp-statistics/App/another_functions.py" in razbor_stroki
65. elem[len(elem) - 1] = elem[len(elem) - 1][:15]

File "/usr/local/lib/python2.7/dist-packages/pyparsing.py" in getitem
390. return self.__toklist[i]

Exception Type: IndexError at /
Exception Value: list index out of range

**Comment by npatyur** [comment]
1. Не понятно, зачем нужен цикл https://github.com/OSLL/mooc-lp-statistics/blob/master/App/another_functions.py#L64. В нем была ошибка - выход за пределы массива. Добавлена проверка длины массива.
2. Не парсятся события вида [2017-05-01 19:06:44.369050137+03:00][23830]: 8ef0de17-a8ab-45b8-bc56-7a4d5a5fe590 check finished, exit_code = 0

**Comment by zmm** [comment]
для обсуждения : 
- похоже это костыль к правилам парсинга выше
- проблема в том, что используется несколько правил для парсинга вместо одного (взять все что слева и справа от первого двоеточия) https://github.com/OSLL/mooc-lp-statistics/blob/b2af96eb85369124317186354d61b4247290a030/App/another_functions.py#L34
- Проблема в strptime https://github.com/OSLL/mooc-lp-statistics/blob/b2af96eb85369124317186354d61b4247290a030/App/another_functions.py#L74
