### ISSUE TITLE
Скрипты запуска тестов должны сигнализировать через exit code об упавших тестах

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#114]
Необходимо чтобы  scripts/run_unittest.sh и scripts/run_selenium_tests.sh возвращали код 1, если количество упавших тестов больше нуля.

**Comment by npatyur** [comment]
pull request:
https://github.com/OSLL/mooc-lp-statistics/pull/120
scripts/run_unittest.sh - дописан
scripts/run_selenium_tests.sh - удален как нерабочий
