### ISSUE TITLE
Нажатие на элемент списка событий открывает /get_log_entry в новой вкладке

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#119]

**Comment by npatyur** [comment]
pull request https://github.com/OSLL/mooc-lp-statistics/pull/133

**Comment by zmm** [comment]
элементы лога не открываются в новой вкладке при нажатии на них. возможно у них отсутствует атрибут target=_blank

**Comment by npatyur** [comment]
добавлен атрибут.
Pull request 
https://github.com/OSLL/mooc-lp-statistics/compare/119_get_log_entry?expand=1
