### ISSUE TITLE
cron скрипт для периодического вызова update_log_in_db

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#130]

**Comment by npatyur** [comment]
pull request
https://github.com/OSLL/mooc-lp-statistics/pull/136

**Comment by zmm** [comment]
Попытался смержить пулл-реквест, но в ветке конфликты. Поправьте их пожалуйста.

**Comment by npatyur** [comment]
pull request
https://github.com/OSLL/mooc-lp-statistics/pull/148/files
