### ISSUE TITLE
Кнопка для обновления содержимого БД в веб-интерфейсе

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#131]
При загрузке страницы необходимо показывать кнопку (активную/неактивную) для подкачки данных в БД из лога. Если в логе есть новые данные - кнопка активная, иначе неактивная.

**Comment by npatyur** [comment]
pull reqest
https://github.com/OSLL/mooc-lp-statistics/pull/135/files

Пока не сделано: активность/неактивность кнопки

**Comment by zmm** [comment]
Смержил пулл-реквест

**Comment by npatyur** [comment]
pull request
https://github.com/OSLL/mooc-lp-statistics/pull/142
