### ISSUE TITLE
Отображение временной зависимости в виде столбчатой диаграммы

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#41]
Насколько сложно отобразить временную зависимость в виде столбчатой диаграммы (примерно такой http://www.bbc.co.uk/staticarchive/60120681c0d19d0c291a5c7cbb557ed6df5a40da.gif) ?

**Comment by ArturAzarau** [comment]
Думаю,что не особо сложно. Попытаюсь сделать.

**Comment by ArturAzarau** [comment]
Теперь отображение выглядит так.
