### ISSUE TITLE
Настраиваемый путь к логу в App/another_functions.py

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#44]
- добавить файл с настройками (settings.json  в директории проекта)
- при запуске приложения из него брать параметр log_file_path и класть в константу LOG_FILE_PATH
- далее читать используя эту константу
- при деплое (scripts/local_deploy.sh) необходимо проверять наличие файла settings.json  и если он существует, то не перезаписывать его.

**Comment by ArturAzarau** [comment]
Вот это непонятно как сделать

**Comment by npatyur** [comment]
Нужно обсудить https://github.com/OSLL/mooc-lp-statistics/pull/96

**Comment by npatyur** [comment]
Новый pull request с другой веткой:
https://github.com/OSLL/mooc-lp-statistics/pull/97

**Comment by zmm** [comment]
возникла проблема вот с таким логом
[pdaemon.txt](https://github.com/OSLL/mooc-lp-statistics/files/972736/pdaemon.txt)

Environment:


Request Method: GET
Request URL: http://mooc-lp-statistics/

Django Version: 1.9.4
Python Version: 2.7.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'App',
 'rest_framework']
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware']



Traceback:

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/mooc-lp-statistics/App/views.py" in home
  32.     list_of_result_lists = App.another_functions.parsing()

File "/var/www/mooc-lp-statistics/App/another_functions.py" in parsing
  80.         list_of_result_lists += [razbor_stroki(line)]

File "/var/www/mooc-lp-statistics/App/another_functions.py" in razbor_stroki
  65.             elem[len(elem) - 1] = elem[len(elem) - 1][:15]

File "/usr/local/lib/python2.7/dist-packages/pyparsing.py" in __getitem__
  390.             return self.__toklist[i]

Exception Type: IndexError at /
Exception Value: list index out of range
