### ISSUE TITLE
Отображение "хвостов" событий в stackedc bar chart

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#59]
Необходимо изменить отображение bar chart для одного события так, чтобы всегда (для любых событий) отображался именно bar chart, а не stacked bar chart для различных написаний события.

При отображении нескольких событий должен отображаться stacked bar chart, у которого каждая секция это общая статистика по конкретному событию.

**Comment by ArturAzarau** [comment]
отображение лежит в файле mooc-lp-statistics-new/App/static/js/js_for_home_page.js
