### ISSUE TITLE
Вывод всплывающего сообщения, если фильтры времени и событий не заполненны

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#70]
Необходимо, чтобы если человек не все заполнил в фильтрах и нажал на "Показать результаты", то ему бы показывалось всплывающее сообщение с информацией, какие поля он забыл заполнить. 

Как сделать всплывающее сообщение https://www.w3schools.com/bootstrap/bootstrap_alerts.asp

**Comment by npatyur** [comment]
pull request:
https://github.com/OSLL/mooc-lp-statistics/pull/84
