### ISSUE TITLE
Уместить содержимое страницы в одном экране (убрать горизонтальный скролл-бар)

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#71]
Сейчас, если произвести фильтрацию, то содержимое сайта начинает расти в ширину и появляется горизонтальный скроллбар. 
В тоже время, у нас используется bootstrap, который по идее должен все отображать адаптивно (без горизонтального скролл-бара).

**Comment by npatyur** [comment]
https://github.com/OSLL/mooc-lp-statistics/pull/95
