### ISSUE TITLE
Selenium-тест для сценария использования с несколькими формами ввода

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#74]
Необходимо в тесте проверить следующую последовательность действий:
- создать несколько полей ввода нажимая на +
- убедиться что они появились
- удалить два 
- убедиться что они исчезли
- заполнить поля ввода валидными событиями
- заполнить фильтр времени валидными событиями
- нажать "Показать результаты"
- убедиться, что отображаются верные результаты

**Comment by npatyur** [comment]
pull request https://github.com/OSLL/mooc-lp-statistics/pull/99
Не реализован пункт "убедиться, что отображаются верные результаты"
