### ISSUE TITLE
Пример для MongoDb

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#76]
Необходимо почитать и посмотреть с помощью БД проекта, что делают следующие запросы:
- db.collect.find()
- db.collect.find({ "Event": {"$in": [" string1", "string2"]}})
- db.collect.find({"Time": {"$gte":ISODate("2016-05-13T15:25:01.908Z")}})

db.collect.aggregate(
                [
                    {
                        "$match": {
                            "Event": {"$in": events},
                            "Time": {"$gte": date_from, "$lte": date_to}
                        }
                    },
                    {
                        "$group": {
                            "_id": {"year": {"$year": "$Time"}, "month": {"$month": "$Time"},
                                    "day": {"$dayOfMonth": "$Time"}, "hour": {"$hour": "$Time"},"Event": "$Event"},
                            "count": {"$sum": 1}
                        }
                    },

Как подключиться (в командной строке):  mongo local

**Comment by zmm** [comment]
https://docs.mongodb.com/manual/reference/method/db.collection.find/
https://docs.mongodb.com/manual/aggregation/

**Comment by zmm** [comment]
https://docs.mongodb.com/manual/reference/sql-comparison/

**Comment by npatyur** [comment]
Создана страница wiki
https://github.com/OSLL/mooc-lp-statistics/wiki/MongoDB:-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B2
