### ISSUE TITLE
Пример простого selenium-теста

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#77]
- Попробовать локально запустить тесты: python App/selenium_test/main.py http://mooc-lp-statistics/
- изучить примеры https://github.com/OSLL/mooc-lp-statistics/tree/master/App/selenium_test
- написать простейший тест (который создает 5 полей ввода нажимая на кнопку +)

**Comment by npatyur** [comment]
wiki:
https://github.com/OSLL/mooc-lp-statistics/wiki/%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA-Selenium-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2-%D0%B2-Firefox

**Comment by npatyur** [comment]
Pull request
https://github.com/OSLL/mooc-lp-statistics/pull/79
