### ISSUE TITLE
Юниттест для фильтрации по нескольким событиям

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#86]
Необходимо сделать юниттест, который будет проверять работу функции pickup_from_database для сценариев когда Events задано массивом

**Comment by npatyur** [comment]
pull request
https://github.com/OSLL/mooc-lp-statistics/pull/90

**Comment by npatyur** [comment]
Новый pull request https://github.com/OSLL/mooc-lp-statistics/pull/98

**Comment by zmm** [comment]
1. Необходимо во всех файлах python указывать заголовок с кодировкой utf-8, иначе бывает вот так:
vood@vood-ThinkPad:~/ws/mooc-lp-statistics/App/unittest$ python test_pickup_from_database_events.py
  File "test_pickup_from_database_events.py", line 33
SyntaxError: Non-ASCII character '\xd0' in file test_pickup_from_database_events.py on line 33, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
2. Для запуска юниттестов нужен отдельный скрипт в scripts

**Comment by npatyur** [comment]
Готово.

**Comment by zmm** [comment]
Наталья, остался последний штрих - давайте сделаем так, чтобы в базу не записывались русские символы, иначе придется возиться с конвертацией. 

==================== UNITTESTS =====================

test_pickup_from_database_events (test_pickup_from_database_events.TestPickupFromDatabaseEvents) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.803s

OK
События в тестовой базе: 'Test_Event_1', 'Test_Event_11','Test_Event_2','Test_Event_3'
('\xd0\xa2\xd0\xb5\xd1\x81\xd1\x82\xd0\xb8\xd1\x80\xd1\x83\xd0\xb5\xd0\xbc\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbe\xd0\xb1\xd1\x8b\xd1\x82\xd0\xb8\xd1\x8f', ['Test_Event_1', 'Test_Event_2'])
('\xd0\x9a\xd0\xbe\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe \xd1\x81\xd0\xbe\xd0\xb1\xd1\x8b\xd1\x82\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xbb\xd1\x8f \xd0\xb3\xd1\x80\xd0\xb0\xd1\x84\xd0\xb8\xd0\xba\xd0\xb0 = ', 2)
("count \xd0\xb4\xd0\xbb\xd1\x8f \xd1\x81\xd0\xbe\xd0\xb1\xd1\x8b\xd1\x82\xd0\xb8\xd1\x8f 'Test_Event_1' = ", 2)
test_pickup_from_database_events (test_pickup_from_database_events.TestPickupFromDatabaseEvents) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.803s

OK
События в тестовой базе: 'Test_Event_1', 'Test_Event_11','Test_Event_2','Test_Event_3'
('\xd0\xa2\xd0\xb5\xd1\x81\xd1\x82\xd0\xb8\xd1\x80\xd1\x83\xd0\xb5\xd0\xbc\xd1\x8b\xd0\xb5 \xd1\x81\xd0\xbe\xd0\xb1\xd1\x8b\xd1\x82\xd0\xb8\xd1\x8f', ['Test_Event_1', 'Test_Event_2'])
('\xd0\x9a\xd0\xbe\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe \xd1\x81\xd0\xbe\xd0\xb1\xd1\x8b\xd1\x82\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xbb\xd1\x8f \xd0\xb3\xd1\x80\xd0\xb0\xd1\x84\xd0\xb8\xd0\xba\xd0\xb0 = ', 2)
("count \xd0\xb4\xd0\xbb\xd1\x8f \xd1\x81\xd0\xbe\xd0\xb1\xd1\x8b\xd1\x82\xd0\xb8\xd1\x8f 'Test_Event_1' = ", 2)
