### ISSUE TITLE
Исправить отображение нескольких событий на временной зависимости в веб-интерфейсе

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#87]
- Необходимо понять, что проще с точки зрения js кода - отображать stacked bar chart или показывать несколько столбцов для разных событий рядом
- Исправить отображение таким образом, чтобы количество событий на графике было меньше или равно числу строк в фильтре.

**Comment by npatyur** [comment]
pull request
https://github.com/OSLL/mooc-lp-statistics/pull/92
