### ISSUE TITLE
Задание периода группировки в веб-интерфейсе

### ISSUE THREAD

**Issue by zmm** [OSLL/mooc-lp-statistics#94]
Необходимо:
- добавить в ui выпадающий список со списком час, день, неделя, месяц
- добавить корректное отображение разных периодов на графике
- добавить обработку параметра в бакенд (/get)

**Comment by npatyur** [comment]
**По пункту**: добавить в ui выпадающий список со списком час, день, неделя, месяц
Функция pickup_from_database() реализована с параметрами час, день, месяц, **год**
Поэтому сделано именно с этими значениями.

pull request: https://github.com/OSLL/mooc-lp-statistics/pull/113
